# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: symphonies-development

test:
  adapter: postgresql
  database: symphonies-test

production:
  adapter: postgresql
  database: symphonies-production
